### ISSUE TITLE
Could you upload the CAD data OR modify the parts to fit the trident?

### ISSUE THREAD

**Issue by W141-ID** [RepRapster/Voron2.4-Twin-Screw-Idler-Mod#2]
As far as I know the trident and the v2.4 have the same idler dimesions.

There a just two minor differences:
- no "belt theeth" on the upper part
- no M5 instead of M3 bolt on the lower part

Would be greatful if you could do those minor changes or upload the cad parts and I would do it myself.
Thanks in advance!

**Comment by RepRapster** [comment]
Hi, Sorry for the delay, i have been busy installing an off grid solar system to my house but i have now modified the Trident front idlers to Twin Screw Idlers and have uploaded to the 2.4 idler mod repository, they are untested as my Trident build is still at the sourcing stage but screw positions are the same as the 2.4 idlers so should work fine....
